<AudioTool>
  orientation: 'vertical'
  Label:
    id: display_label
    text: ''

  BoxLayout:
    size_hint: 1, .2
    TextInput:
      id: user_input
      text: '0'
      on_text: root.enforce_numeric()
  BoxLayout:
    Button:
      id: start_button
      text: 'Start Recording'
      on_release: root.startRecording_clock()
    Button:
      id: stop_button
      text: 'Reproducir'
      on_release: root.stopRecording()
      disabled: True
 
